// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/equipped/v4/:userId.json": {
    params: {
      "userId": string;
    };
  };
  "/api/equipped/v5/:userId.json": {
    params: {
      "userId": string;
    };
  };
  "/translations/:language.json": {
    params: {
      "language": string;
    };
  };
  "/api/inventory/:userId.json": {
    params: {
      "userId": string;
    };
  };
  "/api/increment-item-stattrak": {
    params: {};
  };
  "/api/action/reset-inventory": {
    params: {};
  };
  "/api/action/import-inspect-link": {
    params: {};
  };
  "/api/action/preferences": {
    params: {};
  };
  "/api/action/unlock-case": {
    params: {};
  };
  "/api/consume-item-spray": {
    params: {};
  };
  "/sign-in/steam/callback": {
    params: {};
  };
  "/api/sign-in/callback": {
    params: {};
  };
  "/api/action/resync": {
    params: {};
  };
  "/api/add-container": {
    params: {};
  };
  "/api/user/:userId": {
    params: {
      "userId": string;
    };
  };
  "/api/action/sync": {
    params: {};
  };
  "/api/add-item": {
    params: {};
  };
  "/index.html": {
    params: {};
  };
  "/api/sign-in": {
    params: {};
  };
  "/app.webmanifest": {
    params: {};
  };
  "/api/users": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/sign-out": {
    params: {};
  };
  "/healthz": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/craft": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/equipped/v4/:userId.json" | "/api/equipped/v5/:userId.json" | "/translations/:language.json" | "/api/inventory/:userId.json" | "/api/increment-item-stattrak" | "/api/action/reset-inventory" | "/api/action/import-inspect-link" | "/api/action/preferences" | "/api/action/unlock-case" | "/api/consume-item-spray" | "/sign-in/steam/callback" | "/api/sign-in/callback" | "/api/action/resync" | "/api/add-container" | "/api/user/:userId" | "/api/action/sync" | "/api/add-item" | "/index.html" | "/api/sign-in" | "/app.webmanifest" | "/api/users" | "/settings" | "/sign-out" | "/healthz" | "/sign-in" | "/craft" | "/api/*" | "/*";
  };
  "routes/api.equipped.v4.$userId[.]json._index.tsx": {
    id: "routes/api.equipped.v4.$userId[.]json._index";
    page: "/api/equipped/v4/:userId.json";
  };
  "routes/api.equipped.v5.$userId[.]json._index.tsx": {
    id: "routes/api.equipped.v5.$userId[.]json._index";
    page: "/api/equipped/v5/:userId.json";
  };
  "routes/translations.$language[.]json._index.tsx": {
    id: "routes/translations.$language[.]json._index";
    page: "/translations/:language.json";
  };
  "routes/api.inventory.$userId[.]json._index.tsx": {
    id: "routes/api.inventory.$userId[.]json._index";
    page: "/api/inventory/:userId.json";
  };
  "routes/api.increment-item-stattrak._index.tsx": {
    id: "routes/api.increment-item-stattrak._index";
    page: "/api/increment-item-stattrak";
  };
  "routes/api.action.reset-inventory._index.tsx": {
    id: "routes/api.action.reset-inventory._index";
    page: "/api/action/reset-inventory";
  };
  "routes/api.action.import-inspect-link.tsx": {
    id: "routes/api.action.import-inspect-link";
    page: "/api/action/import-inspect-link";
  };
  "routes/api.action.preferences._index.tsx": {
    id: "routes/api.action.preferences._index";
    page: "/api/action/preferences";
  };
  "routes/api.action.unlock-case._index.tsx": {
    id: "routes/api.action.unlock-case._index";
    page: "/api/action/unlock-case";
  };
  "routes/api.consume-item-spray._index.tsx": {
    id: "routes/api.consume-item-spray._index";
    page: "/api/consume-item-spray";
  };
  "routes/sign-in.steam.callback._index.tsx": {
    id: "routes/sign-in.steam.callback._index";
    page: "/sign-in/steam/callback";
  };
  "routes/api.sign-in.callback._index.tsx": {
    id: "routes/api.sign-in.callback._index";
    page: "/api/sign-in/callback";
  };
  "routes/api.action.resync._index.tsx": {
    id: "routes/api.action.resync._index";
    page: "/api/action/resync";
  };
  "routes/api.add-container._index.tsx": {
    id: "routes/api.add-container._index";
    page: "/api/add-container";
  };
  "routes/api.user.$userId._index.tsx": {
    id: "routes/api.user.$userId._index";
    page: "/api/user/:userId";
  };
  "routes/api.action.sync._index.tsx": {
    id: "routes/api.action.sync._index";
    page: "/api/action/sync";
  };
  "routes/api.add-item._index.tsx": {
    id: "routes/api.add-item._index";
    page: "/api/add-item";
  };
  "routes/index[.]html._index.tsx": {
    id: "routes/index[.]html._index";
    page: "/index.html";
  };
  "routes/api.sign-in._index.tsx": {
    id: "routes/api.sign-in._index";
    page: "/api/sign-in";
  };
  "routes/app[.]webmanifest.tsx": {
    id: "routes/app[.]webmanifest";
    page: "/app.webmanifest";
  };
  "routes/api.users._index.tsx": {
    id: "routes/api.users._index";
    page: "/api/users";
  };
  "routes/settings._index.tsx": {
    id: "routes/settings._index";
    page: "/settings";
  };
  "routes/sign-out._index.tsx": {
    id: "routes/sign-out._index";
    page: "/sign-out";
  };
  "routes/healthz._index.tsx": {
    id: "routes/healthz._index";
    page: "/healthz";
  };
  "routes/sign-in._index.tsx": {
    id: "routes/sign-in._index";
    page: "/sign-in";
  };
  "routes/craft._index.tsx": {
    id: "routes/craft._index";
    page: "/craft";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api.$.tsx": {
    id: "routes/api.$";
    page: "/api/*";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.equipped.v4.$userId[.]json._index": typeof import("./app/routes/api.equipped.v4.$userId[.]json._index.tsx");
  "routes/api.equipped.v5.$userId[.]json._index": typeof import("./app/routes/api.equipped.v5.$userId[.]json._index.tsx");
  "routes/translations.$language[.]json._index": typeof import("./app/routes/translations.$language[.]json._index.tsx");
  "routes/api.inventory.$userId[.]json._index": typeof import("./app/routes/api.inventory.$userId[.]json._index.tsx");
  "routes/api.increment-item-stattrak._index": typeof import("./app/routes/api.increment-item-stattrak._index.tsx");
  "routes/api.action.reset-inventory._index": typeof import("./app/routes/api.action.reset-inventory._index.tsx");
  "routes/api.action.import-inspect-link": typeof import("./app/routes/api.action.import-inspect-link.tsx");
  "routes/api.action.preferences._index": typeof import("./app/routes/api.action.preferences._index.tsx");
  "routes/api.action.unlock-case._index": typeof import("./app/routes/api.action.unlock-case._index.tsx");
  "routes/api.consume-item-spray._index": typeof import("./app/routes/api.consume-item-spray._index.tsx");
  "routes/sign-in.steam.callback._index": typeof import("./app/routes/sign-in.steam.callback._index.tsx");
  "routes/api.sign-in.callback._index": typeof import("./app/routes/api.sign-in.callback._index.tsx");
  "routes/api.action.resync._index": typeof import("./app/routes/api.action.resync._index.tsx");
  "routes/api.add-container._index": typeof import("./app/routes/api.add-container._index.tsx");
  "routes/api.user.$userId._index": typeof import("./app/routes/api.user.$userId._index.tsx");
  "routes/api.action.sync._index": typeof import("./app/routes/api.action.sync._index.tsx");
  "routes/api.add-item._index": typeof import("./app/routes/api.add-item._index.tsx");
  "routes/index[.]html._index": typeof import("./app/routes/index[.]html._index.tsx");
  "routes/api.sign-in._index": typeof import("./app/routes/api.sign-in._index.tsx");
  "routes/app[.]webmanifest": typeof import("./app/routes/app[.]webmanifest.tsx");
  "routes/api.users._index": typeof import("./app/routes/api.users._index.tsx");
  "routes/settings._index": typeof import("./app/routes/settings._index.tsx");
  "routes/sign-out._index": typeof import("./app/routes/sign-out._index.tsx");
  "routes/healthz._index": typeof import("./app/routes/healthz._index.tsx");
  "routes/sign-in._index": typeof import("./app/routes/sign-in._index.tsx");
  "routes/craft._index": typeof import("./app/routes/craft._index.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/api.$": typeof import("./app/routes/api.$.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};